### ISSUE TITLE
Facial morphs not working in C4D R23?

### ISSUE THREAD

**Issue by FortniteStuff** [daz3d/DazToC4D#12]
So after doing auto-IK to the new Genesis 8.1 model from DAZ i can't seem to get the created facial morph linked..

Morph tag is set to animate, and i do see animation on the pose morph tag sliders, but nothing seems to happen when linked. Only thing i can think of is that it's because i'm on R23 or it's the model i'm using..

Also, since i'm new to morph tags i'm not entirely sure i am linking the correct objects..

Screenshot for reference:
https://gyazo.com/e0bf0a01a31fb0e4e6faa647bb8e0cee

**Comment by Popinjayishuman** [comment]
https://www.youtube.com/watch?v=wQTrMXzhIHk&t=11s

This video documents the new process for linking morphs and using moves by maxon. Hope this helps!

**Comment by jamslut** [comment]
> 

I went through this video, it still doesn't work.
