### ISSUE TITLE
Good News / Bad News on DazToC4D

### ISSUE THREAD

**Issue by didpublishing** [daz3d/DazToC4D#13]
Let's start with the good news: I loaded DazToC4D on different builds of C4D starting with r19 to r24. All successfully loaded a figure.
r19 - I was successful in loading Genesis 8 with updated textures and IK controls in the A  and the T pose. 
I tried to repeat the process with Genesis 8.1 but kept getting loading errors for IK controls. 
I moved on to try the other builds.
r21 - r24 worked pretty much the same.

**Comment by Popinjayishuman** [comment]
Could you send us some screenshots of errors you are seeing on different builds? That would be a huge help for testing and fixing!
