### ISSUE TITLE
Redshift Materials not being converted properly.

### ISSUE THREAD

**Issue by schneigui** [daz3d/DazToC4D#14]
Red shift materials are not being converted on this version. Any updates on fixing this? Also, how can I get back to a previous version without this issue? Thanks

**Comment by Popinjayishuman** [comment]
You can get old versions of the bridge here: https://github.com/daz3d/DazToC4D/releases

As for the other issue we will look into it.

**Comment by Popinjayishuman** [comment]
The newest update should now have support for redshift!
