### ISSUE TITLE
Bridge not working at all

### ISSUE THREAD

**Issue by Brodgah** [daz3d/DazToC4D#20]
The DazToC4D bridge is not working for me at all and wondering how to fix it. The materials do not convert over to octane, instead they convert grey and metallic. When I export out a character in a pose or with hair materials that have been edited, the character goes back to its original t pose OR it imports I’m with massive geometric issues with fingers super long and face super distorted. How can I get an older version of DazToC4D bridge?

**Comment by Brodgah** [comment]
Furthermore,  I have seen no fix to this on Daz part in the forums. I talked to someone that uses Daz in many renders using c4d and octane and they told me to uninstall new bridge and manually install an old bridge and it will fix itself. Can someone PLEASE provide me with an old bridge file - I feel like I just wasted $60 on this company.

**Comment by samjay3d** [comment]
Sorry to hear about the problem this has caused currently we only support standard and redshift in the newest version of the bridge. As we are are needing to rework the internals of the bridge I hope you understand in do time you will have octane working again in future updates until then here is the old version and instructions can be found here. 

https://www.daz3d.com/forums/discussion/497181/daz-to-cinema-4d-beta-how-to-download-release-versions-manually-install-and-replace-old-installs/p1

To get the older version  you can download it here. 
https://github.com/daz3d/DazToC4D/releases/tag/1.1
If you have further trouble our CS Member, Ryan can answer any questions you have through a ticket. Have a great day!

**Comment by Brodgah** [comment]
Hi, the manual instal link is taking me to a gateway code now - i saw it
before and now its not working. Also, the directions didnt make a ton of
sense.

**Comment by Popinjayishuman** [comment]
https://helpdaz.zendesk.com/hc/en-us/requests/new

If you follow this link you can create a ticket for installation help with our customer service department. Best of luck!
