### ISSUE TITLE
C4D extension not appearing in R22

### ISSUE THREAD

**Issue by Tortillaguy** [daz3d/DazToC4D#21]
Hello,  I'm trying to install the Bridge using Daz Studio 4.15 and Cinema 4D S22
I selected R22 when I installed the bridge and pointed it to my "Maxon Cinema 4D R22" folder.
I can confirm there is a folder named "DazToC4D" inside the "plugins" folder, however when I run C4D I do not see the extension listed. 

I can see my Octane extension fine so I'm wondering what could be the issue here? 
Any help would be appreciated. Thanks!

**Comment by Popinjayishuman** [comment]
Hey there Tortillaguy, did you install C4d manually or through the maxon app? From what we can see python is not installing correctly when using the maxon app however when installing with the offline installer the plugin worked, this appears to be an issue with the maxon installer and python.

**Comment by Tortillaguy** [comment]
Thanks for responding! Totally makes sense why that would be the case. I'll try re-installing through the maxon app and see how it goes.

**Comment by Tortillaguy** [comment]
The plugins working! Thanks for keeping this open.
