### ISSUE TITLE
Overwriting plugin folder on installation

### ISSUE THREAD

**Issue by xanathon** [daz3d/DazToC4D#22]
The last version did overwrite the local plugin folder. In my case the plugin folder in the prefs folder is only a hardlink to another folder on the hdd that is shared by multiple versions of C4D.

The installer did not honor that and just overwrote the link, practically removing all my plugins until I recreate the link.

It is unbelievable unprofessional and amateur-like anyway that DAZ installer does it this way, it should honor the hardlinks if they are there.

I asked about it in the forums but never got any answer whatsoever from DAZ support, so I have to ask here, as this happens, when installing this plugin and so is definitely an issue of the plugin.

**Comment by Popinjayishuman** [comment]
Unfortunately this is an issue that needs to be fixed by the Daz Studio team, they are aware of it however the team is working hard on the Big Sur update. Sorry we can't be of more help.
