### ISSUE TITLE
DAZ plugin does not load in MacOS 10.13

### ISSUE THREAD

**Issue by nagra00** [daz3d/DazToC4D#31]
The new C++ plugin does not load in MacOS 10.13 HighSierra (maybe build with wrong library version/framework).

I use DAZ studio 4.20.0.2 and here is the output from the about installed plugins dialog:
![daz2c4d](https://user-images.githubusercontent.com/85390915/174583630-320e09ec-4d44-4338-8635-9ac0135f54b6.jpg)

Regards,
Stefan

**Comment by danielbui78** [comment]
Hi Stefan,

Can you please try using Daz Install Manager to install the plugin and let me know if that works?  https://www.daz3d.com/install-manager-info  The version available there is actually the latest Mac version and should be named "libdzbridgec4d.dylib".  Any file named "libdzbridge_c4d.dylib" is out of date.

If it is still not working, or you are unable to use the Daz Install Manager then please let me know the following details:
1. Date Modified of the C4D dylib file
2. Size in bytes of the C4D dylib file (use the command-I or File -> Get Info option from Finder)
3. Following information from the "System Information" app (from main menu, select Apple -> About This Mac, then click "System Report...")
    1. Model Name and Model Identifier
    2. Processor Name
    3. Memory
    4. Available Disk Space reported by Finder

**Comment by nagra00** [comment]
Using install manager makes no difference, still not working.

Installed by DAZ3DIM:

libdzc4dbridge.dylib: 9.754.960 Byte, 9. Juni 2022 at 08:41

System info:

Modellname:	Mac Pro
Modell-Identifizierung:	MacPro5,1
Prozessortype:	6-Core Intel Xeon (X5680 @ 3.33GHz)
Memory:	96 GB

I run otool to check dependencies of the lib, looks ok to me:

otool -L libdzc4dbridge.dylib 

libdzc4dbridge.dylib:
	@rpath/libdzbridge_c4d.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.1)
	@rpath/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.1)
	@rpath/QtScript.framework/Versions/4/QtScript (compatibility version 4.8.0, current version 4.8.1)
	@rpath/QtNetwork.framework/Versions/4/QtNetwork (compatibility version 4.8.0, current version 4.8.1)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 164.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1109.101.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	@rpath/libdzcore.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)

**Comment by danielbui78** [comment]
I have uploaded a fresh Mac binary for the latest version: https://github.com/daz3d/DazToC4D/releases/tag/2022.1.8

Please download that dylib and see if it works for you.  It is built with XCode 13 on an Intel Mac with Big Sur.  I have double-checked to make sure that the Deployment target is 10.9.  If this does not work, could you please test the DazToBlender plugin on your mac to see if it will load?  Thank you

**Comment by nagra00** [comment]
No does not load, same as with previous version.

I installed the daz2blender plugin using DAZ3DIM and it does not load either.

**Comment by danielbui78** [comment]
OK, thank you for reporting this, can you send me you DAZStudio log.txt file?  Help->Troubleshooting->View Log File...

**Comment by nagra00** [comment]
Here is the relevant part of the log:

2022-06-20 16:58:39.443 [INFO] :: 	libdzc4dbridge.dylib
2022-06-20 16:58:39.445 [INFO] :: 	/Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib failed to load
2022-06-20 16:58:39.445 [INFO] :: Error: dlopen(/Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib

Same issue with the blender plugin.

**Comment by nagra00** [comment]
I downloaded all needed libs and SDKs but the QT 4.8.1 installer refuses to work on MacOS 10.13.

So i gave up.

**Comment by danielbui78** [comment]
I have verified that MacOS 10.12 works and 11.x and 12.x work.  The problem seems to be related to an issue with the gnu c++ standard libraries that is shipped with 10.13.  I am trying to remove all dependencies that require gnu c++ and only use clang++.  Hopefully this will resolve the issue.  It will take some time.

**Comment by nagra00** [comment]
No, not working here. Same unresolved symbol + complain that it is build for MacOS 10.15:

2022-06-20 14:50:50.154 [INFO] :: 	libdzc4dbridge.dylib
2022-06-20 14:50:50.180 [INFO] :: 	/Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib failed to load
2022-06-20 14:50:50.180 [INFO] :: Error: dlopen(/Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/DAZ 3D/DAZStudio4 64-bit v4.20.0.2/plugins/libdzc4dbridge.dylib

**Comment by nagra00** [comment]
Did a quick serrch.

According to this thread:  https://stackoverflow.com/questions/58426186/dyld-symbol-not-found-chkstk-darwin

"CMake is having a very hard time setting the Base SDK option on the project."

That example was for an iOS build but i guess its a general CMake problem.

**Comment by danielbui78** [comment]
@nagra00 
I have a high degree of confidence that this will finally work: 
https://github.com/daz3d/DazToC4D/releases/download/2022.1.8/libdzc4dbridge.dylib.v2022.1.8.21.zip

The problem turned out to be due to linking with FbxSDK 2020, which requires System 10.15+.  I downgraded to FbxSDK2015.1 which should support 10.13.  Thanks for your patience.

**Comment by nagra00** [comment]
Yes that fixed it !

Material conversion to Redshift is currently a NOP, is that intentional for this version?
Just asking, i have my own conversion script so no big deal.

**Comment by danielbui78** [comment]
Sorry, I will need to review the Redshift code pathway to make a proper assessment.  If you are still having issues, please open a new issue for it.

I am glad 10.13 is working for you.  If you have no further issues regarding MacOS 10.13, then I will close this issue. Thanks

**Comment by nagra00** [comment]
no more issues with MacOS 10.13 so far. 
Anyway exporting environments has the same pivot issues like regular FBX export and on top exported materials are worse.  Non genesis figures (e.g. articulated vehicles) do not work using the bridge --> i switched back to normal FBX export.
