### ISSUE TITLE
[Windows 10] Installation ignores symlinks and overwrites them

### ISSUE THREAD

**Issue by xanathon** [daz3d/DazToC4D#5]
This is a critical problem.

The installation routine installs the C4D plugin forcibly into the standard C4D plugin location, creating a "plugins" folder, if none is there. In my case there is a symlink in that position, leading to another folder where the plugins actually are. There are multiple causes for doing it this way, one of them to be able to use the plugins from multiple C4D versions (yes, I know that I can set the plugin folder location in the C4D prefs, but that leads to other problems, and symlinks are a tested solution on Windows).

The installation routine needs to honor that symlink, instead of simply overwriting it with a new plugins folder, that is standard Windows functionality and I have no idea how a behaviour like this get's through QA. Every time I install an update all my plugins vanish, since again the symlink was overwritten by the installation routine. This is highly annoying.

If the installation routine is not able to do this correct (and I guess it is probably created by the DAZ people not knowing what they do), at least there needs to be a dialogue asking for an installation folder instead of simply overwriting stuff.

**Comment by samjay3d** [comment]
This is actually a feature request for the Install Manager/Daz Central. We brought it up with the person in charge of that and recommended you make a feature request for it.  

https://helpdaz.zendesk.com/hc/en-us/requests/new

**Comment by xanathon** [comment]
Are you kidding me? This installation fucks with my system and you close the issue? This is not an error, this is a major bug and you should relay it to the proper channels instead of closing it. I know that daz helpdesk, you never get any useful answer whatsoever. If I file the problem there nothng will ne done. The problem occurs at the installation of this bridge, so this is bridge related.
