### ISSUE TITLE
Daz to C4D Bridge triggers Norton 360 and Joints not aligned

### ISSUE THREAD

**Issue by rbrandford** [daz3d/DazToC4D#50]
Just wanted to let you know that the latest release of the bridge (two weeks prior to this message) triggers my virus protection software. Telling the software to ignore it was easy, but I thought you should know.

Also, I don't know what I am doing wrong, but somehow, the joints of my Genesis 8 model are still not aligned properly. If you like I can send screen grabs of my results. Joint alignment issues aside, this is a great plug in.

**Comment by Gurgaljev** [comment]
First a big Thank You for that wonderful project!
It has made a huge leap forward till the last time i tried to use it, with so many great new features making it ful fill almost all needs.

I still have one issue that seems to be what has been described above - the joint rotations seem to be wrong (tested with genesis 9 and 8) - this was something that worked well in earlier versions (with G3 at that time)

What i can add as info is that for some reason when applying IK the joints bend in the right directions - only for the direct controls they do not.
And a second thing i noticed was that when importing the logo of the dialog stays at the picture 'importing, please wait' - while in earlier versions after import it usually went back to the original picture. Maybe this is only the picture but it seems to have stopped the import as the interface can be used again adding IK or convertig textures. So i still have the impression it maybe stopped the import process prematurely as i can remember from earlier versions that correction was the last thing done

**Comment by danielbui78** [comment]
@rbrandford I have scanned the files with McAfee and F-Secure anti-virus tools.  If you perform an MD5 hash on the downloaded zip file and it matches the one I posted, then you can be fairly confident that you are using the exact files that I have uploaded.  If you do not wish to trust my scans, then you can wait for the DIM release which should not trigger any virus protection warnings.

Regarding misaligned joints, make sure that you are not exporting any Morphs that contain any bone length changes.  If they are still misaligned even when you are not exporting Morphs, please send screenshots and detailed steps to reproduce the issue.  Thank you.

**Comment by danielbui78** [comment]
@Gurgaljev 
There are some known issues related to IK not working 100% correctly.  Make sure you send a Daz character in the default pose (click Edit -> Figure -> Zero -> Zero Figure Pose) and without any animations applied, then be sure to click YES to "Fix Bone Orientations" and Yes to "Convert to T-Pose".  This should give you the most reliable results with Auto-IK.  If you have further issues, please start a new Issue thread and post screenshots and detailed steps on how to reproduce.

If the "Importing, please wait" message does not go away, that suggests that the python process may have crashed.  Please go to Extensions -> Console... and check the Python tab to see if there are any error messages.  If you continue to have this problem, please send screenshots and detailed steps to reproduce the issue -- Please also start a new Issue thread to avoid any confusion when helping you further.

**Comment by rbrandford** [comment]
My issue with joint rotations has been resolved. Thanks.
