### ISSUE TITLE
[Redshift] diffuse texture has wrong gamma setting

### ISSUE THREAD

**Issue by xanathon** [daz3d/DazToC4D#8]
When using an (s)rgb image as a texture in a Redshift texture node, the gamma checkbox needs to be activated and gamma needs to be set to 2.2.

This is not done right by the plugin and needs to be corrected. 

Remark: this applies to all color textures, but not for grayscale textures such as bump, roughness and similar.

**Comment by xanathon** [comment]
Addition: On opacity textures the gamma is set to 0.1 for what reason ever ... This is completely wrong. I am just finding more very strange gamma settings throughout imported materials that were converted to Redshift.

As a rule of thumb: you do not touch the gamma settings in the texture node most of the time aside from the cases I outlined in the opening post. If adjustment needs to be done you do it via the adjustment options present in the node or with a subsequent Color Correction node.

**Comment by samjay3d** [comment]
100% I will go through the materials next week as well. Add your recommendation and remove anything using gamma that shouldn't be. 

I think the opacity being affected by gamma was made by the original creator to deal with the opacity masks not working correctly at lower samples of refraction. Obviously not the best approach. I will remove it but, also look into a better approach thanks for the feedback!

**Comment by xanathon** [comment]
I did not yet look at the translucent materials in detail, but those are just created completely wrong and it has nothing to do per se with gamma. They are basically not translucent after import.

Just removing gamma will not do it. Gamma for colored textures needs to be overridden to 2.2, for black & white or normals it should not be touched (stay at 1).

**Comment by samjay3d** [comment]
Yep I get that. Sorry if I wasn't clear. 

I will also look into that as well and see if I can find a solution.

**Comment by samjay3d** [comment]
Putting this on hold until redshift rework is complete.

**Comment by xanathon** [comment]
And that means exactly what?

Is someone even actively working on Redshift support? This is an two months old issue and nothing was done about it. Does "on hold" mean no one works on it?

Why not? The Redshift support has myriads of bus. Is no one at DAZ interested in maintaining the C4D bridge they advertise so much to sell more assets?

What exactly does "Redshift rework" mean? Can you give an ETA?

**Comment by samjay3d** [comment]
https://www.daz3d.com/forums/discussion/497181/daz-to-cinema-4d-beta-how-to-download-release-versions-manually-install-and-replace-old-installs#latest

There has been a bunch of updates actually. This will be on hold and most likely will be just replaced code so the issue will not be prevalent at all. You can check out the new Physical Materials as those are being converted better already.

**Comment by xanathon** [comment]
Let me guess: DAZ still overwrites the plugin folder on installation? That's the cause why I do not install the new version.
