### ISSUE TITLE
Morphs disapear after AUTO-IK

### ISSUE THREAD

**Issue by 0pathfinder0** [daz3d/DazToC4D#9]
Morphs disappear after AUTO-IK. One of the previous versions did not have this problem. Is there a solution?

**Comment by samjay3d** [comment]
This issue should be working in the newest release for more information check out this forum post. 
https://www.daz3d.com/forums/discussion/497181/daz-to-cinema-4d-beta-how-to-download-release-versions-manually-install-and-replace-old-installs#latest
